package team.gif;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.Button;
import edu.wpi.first.wpilibj.buttons.JoystickButton;

/**
 * @author Patrick
 * 
 * This class designates the ports for the joysticks and the location for each button.
 * Buttons can be programmed to run a command in the constructor.
 * DO NOT EDIT THIS FILE WITHOUT PERMISSION. PULL REQUESTS WILL BE REJECTED.
 */
public class OI {
    
	public static final Joystick leftStick = new Joystick(0);
	public static final Joystick rightStick = new Joystick(1);
	public static final Joystick auxStick = new Joystick(2);
	
	private static Button leftTrigger;
	private static Button left2;
	private static Button left3;
	private static Button left4;
	
	private static Button rightTrigger;
	private static Button right2;
	private static Button right3;
	private static Button right4;
	
	private static Button auxTrigger;
	private static Button aux2;
	private static Button aux3;
	private static Button aux4;
	
	public OI() {
		leftTrigger = new JoystickButton(leftStick, 1);
		left2 = new JoystickButton(leftStick, 2);
		left3 = new JoystickButton(leftStick, 3);
		left4 = new JoystickButton(leftStick, 4);
		
		rightTrigger = new JoystickButton(rightStick, 1);
		right2 = new JoystickButton(rightStick, 2);
		right3 = new JoystickButton(rightStick, 3);
		right4 = new JoystickButton(rightStick, 4);
		
		auxTrigger = new JoystickButton(auxStick, 1);
		aux2 = new JoystickButton(auxStick, 2);
		aux3 = new JoystickButton(auxStick, 3);
		aux4 = new JoystickButton(auxStick, 4);
	}
	
}

